### ISSUE TITLE
Have you check the code could be run?

### ISSUE THREAD

**Issue by aries-young** [showlab/datacentric.vlp#2]
Hello, I find you work modified based on BLIP. But, before your uploading, have you checked the published code could be run? Even many simple errors of import....

**Comment by FingerRec** [comment]
Upload more files.

**Comment by robinliu912** [comment]
@aries-young @FingerRec  Hi, have you run the code successfully? I still find some files missing, e.g. `cc3m_training_success_half_itm.json` in *codebook_cluster.py* and several configuration files `caption_coco.yaml` etc.
